label: Texas property taxes
description: Texas property taxes, based on a rounded-up average from a Google search
monthly:
  - label: Texas property taxes estimate
    calculation: 1.9%
    calculation type: monthly value fraction
    identifier: property taxes
